### ISSUE TITLE
No module named 'selenium

### ISSUE THREAD

**Issue by lilongjissg** [bailuWX/MajsoulAI-fix#4]
in script .\majsoul_wrapper\addons.py: No module named 'selenium'

我把selenium的版本回退到了3.141.0也不行，更新到最新也不行

**Comment by lilongjissg** [comment]
哦，原来是pytorch没装好，装好后出现了
in script .\majsoul_wrapper\addons.py: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
好像是protobuf版本的问题

**Comment by lilongjissg** [comment]
把protobuf 升到3.14 解决了。
不过出现了下面的问题
Traceback (most recent call last):
  File "F:\python3.9.7\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\python3.9.7\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\python3.9.7\Scripts\mitmdump.exe\__main__.py", line 7, in <module>
  File "F:\python3.9.7\lib\site-packages\mitmproxy\tools\main.py", line 148, in mitmdump
    from mitmproxy.tools import dump
  File "F:\python3.9.7\lib\site-packages\mitmproxy\tools\dump.py", line 1, in <module>
    from mitmproxy import addons
  File "F:\python3.9.7\lib\site-packages\mitmproxy\addons\__init__.py", line 12, in <module>
    from mitmproxy.addons import onboarding
  File "F:\python3.9.7\lib\site-packages\mitmproxy\addons\onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "F:\python3.9.7\lib\site-packages\mitmproxy\addons\onboardingapp\__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "F:\python3.9.7\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "F:\python3.9.7\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "F:\python3.9.7\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "F:\python3.9.7\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "F:\python3.9.7\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (F:\python3.9.7\lib\site-packages\markupsafe\__init__.py)

**Comment by bailuWX** [comment]
没遇到过这些问题，环境的话推荐3.8的版本。。另外我更新了readme注意事项，可以看看
